apiVersion: 1

datasources:
    - name: InfluxDB
      uid: ids-influxdb
      type: influxdb
      access: proxy
      url: http://influxdb:8086
      isDefault: true
      editable: false
      jsonData:
          version: Flux
          organization: tepegoz
          defaultBucket: ids_data
          httpMode: POST
          tlsSkipVerify: true
      secureJsonData:
          token: ${INFLUXDB_TOKEN}
